/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tutorial_ndkhelloworld_NDKHelloWorldActivity */

#ifndef _Included_com_tutorial_ndkhelloworld_NDKHelloWorldActivity
#define _Included_com_tutorial_ndkhelloworld_NDKHelloWorldActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tutorial_ndkhelloworld_NDKHelloWorldActivity
 * Method:    userName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tutorial_ndkhelloworld_NDKHelloWorldActivity_userName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
