/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tutorial_ndk_NDKExamActivity */

#ifndef _Included_com_tutorial_ndk_NDKExamActivity
#define _Included_com_tutorial_ndk_NDKExamActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tutorial_ndk_NDKExamActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tutorial_ndk_NDKExamActivity_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
